name: Automatic deployment

on:
  push:
    branches: [main]

jobs:
  www:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v24.1
        with:
          files: ./**/*
          files_ignore: ./**/node_modules
      - name: Setup node (conditional)
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: SSH agent (conditional)
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Deploy to Github pages (conditional)
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          USE_SSH: true
        run: |
          git config --global user.email "3356641+jpbourgeon@users.noreply.github.com"
          git config --global user.name "jpbourgeon"
          npm ci --ignore-scripts
          npm run deploy
